/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/tabbar/home" |
       "/pages/about/about" |
       "/pages/about/i18n" |
       "/pages/callback/app" |
       "/pages/demo/detail_demo" |
       "/pages/demo/list_demo" |
       "/pages/game/index" |
       "/pages/tabbar/discover" |
       "/pages/tabbar/game" |
       "/pages/tabbar/mall" |
       "/pages/tabbar/my" |
       "/pages/test/i18n" |
       "/pages/test/index" |
       "/pages/test/safe" |
       "/pages/webview/index" |
       "/pages/cats/about/index" |
       "/pages/cats/address/add" |
       "/pages/cats/address/management" |
       "/pages/cats/address/select" |
       "/pages/cats/agreement/detail" |
       "/pages/cats/asset/log" |
       "/pages/cats/bulletins/detail" |
       "/pages/cats/bulletins/list" |
       "/pages/cats/discord/auth2" |
       "/pages/cats/faq/detail" |
       "/pages/cats/faq/list" |
       "/pages/cats/favorite/list" |
       "/pages/cats/flow/cart" |
       "/pages/cats/flow/confirm_order" |
       "/pages/cats/goods/detail" |
       "/pages/cats/goods/search" |
       "/pages/cats/kf/add" |
       "/pages/cats/login/login" |
       "/pages/cats/login/login_code" |
       "/pages/cats/message/index" |
       "/pages/cats/news/detail" |
       "/pages/cats/notification/detail" |
       "/pages/cats/notification/list" |
       "/pages/cats/order/detail" |
       "/pages/cats/order/list" |
       "/pages/cats/pay/index" |
       "/pages/cats/pay/result" |
       "/pages/cats/pledge/detail" |
       "/pages/cats/pledge/index" |
       "/pages/cats/pledge/ranking" |
       "/pages/cats/posts/list" |
       "/pages/cats/settings/avatar" |
       "/pages/cats/settings/currency" |
       "/pages/cats/settings/index" |
       "/pages/cats/settings/language" |
       "/pages/cats/settings/nickname" |
       "/pages/cats/settings/virtual_account" |
       "/pages/cats/social/detail" |
       "/pages/cats/social/detail_sktiy_comment" |
       "/pages/cats/social/group_chat" |
       "/pages/cats/social/group_members" |
       "/pages/cats/social/publish" |
       "/pages/cats/upload/upload" |
       "/pages/cats/user/home" |
       "/pages/cats/webview/webview" |
       "/pages/cats/login/virtual/bind" |
       "/pages/cats/login/virtual/bind_code" |
       "/pages/cats/login/virtual/login" |
       "/pages/cats/login/virtual/login_code";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tabbar/home" | "/pages/tabbar/mall" | "/pages/tabbar/game" | "/pages/tabbar/discover" | "/pages/tabbar/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
